// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: onvif_firmware_update.proto
#ifndef GRPC_onvif_5ffirmware_5fupdate_2eproto__INCLUDED
#define GRPC_onvif_5ffirmware_5fupdate_2eproto__INCLUDED

#include "onvif_firmware_update.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace onvif_firmware_update {

// The greeter service definition.
class FirmwareUpdate final {
 public:
  static constexpr char const* service_full_name() {
    return "onvif_firmware_update.FirmwareUpdate";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status UpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::onvif_firmware_update::UpdateFirmwareReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::onvif_firmware_update::UpdateFirmwareReply>> AsyncUpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::onvif_firmware_update::UpdateFirmwareReply>>(AsyncUpdateFirmwareRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::onvif_firmware_update::UpdateFirmwareReply>> PrepareAsyncUpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::onvif_firmware_update::UpdateFirmwareReply>>(PrepareAsyncUpdateFirmwareRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a greeting
      virtual void UpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest* request, ::onvif_firmware_update::UpdateFirmwareReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest* request, ::onvif_firmware_update::UpdateFirmwareReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::onvif_firmware_update::UpdateFirmwareReply>* AsyncUpdateFirmwareRaw(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::onvif_firmware_update::UpdateFirmwareReply>* PrepareAsyncUpdateFirmwareRaw(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status UpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::onvif_firmware_update::UpdateFirmwareReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::onvif_firmware_update::UpdateFirmwareReply>> AsyncUpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::onvif_firmware_update::UpdateFirmwareReply>>(AsyncUpdateFirmwareRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::onvif_firmware_update::UpdateFirmwareReply>> PrepareAsyncUpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::onvif_firmware_update::UpdateFirmwareReply>>(PrepareAsyncUpdateFirmwareRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void UpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest* request, ::onvif_firmware_update::UpdateFirmwareReply* response, std::function<void(::grpc::Status)>) override;
      void UpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest* request, ::onvif_firmware_update::UpdateFirmwareReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::onvif_firmware_update::UpdateFirmwareReply>* AsyncUpdateFirmwareRaw(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::onvif_firmware_update::UpdateFirmwareReply>* PrepareAsyncUpdateFirmwareRaw(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateFirmware_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status UpdateFirmware(::grpc::ServerContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest* request, ::onvif_firmware_update::UpdateFirmwareReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateFirmware : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateFirmware() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UpdateFirmware() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateFirmware(::grpc::ServerContext* /*context*/, const ::onvif_firmware_update::UpdateFirmwareRequest* /*request*/, ::onvif_firmware_update::UpdateFirmwareReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateFirmware(::grpc::ServerContext* context, ::onvif_firmware_update::UpdateFirmwareRequest* request, ::grpc::ServerAsyncResponseWriter< ::onvif_firmware_update::UpdateFirmwareReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UpdateFirmware<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_UpdateFirmware : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateFirmware() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::onvif_firmware_update::UpdateFirmwareRequest, ::onvif_firmware_update::UpdateFirmwareReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest* request, ::onvif_firmware_update::UpdateFirmwareReply* response) { return this->UpdateFirmware(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateFirmware(
        ::grpc::MessageAllocator< ::onvif_firmware_update::UpdateFirmwareRequest, ::onvif_firmware_update::UpdateFirmwareReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::onvif_firmware_update::UpdateFirmwareRequest, ::onvif_firmware_update::UpdateFirmwareReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateFirmware() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateFirmware(::grpc::ServerContext* /*context*/, const ::onvif_firmware_update::UpdateFirmwareRequest* /*request*/, ::onvif_firmware_update::UpdateFirmwareReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateFirmware(
      ::grpc::CallbackServerContext* /*context*/, const ::onvif_firmware_update::UpdateFirmwareRequest* /*request*/, ::onvif_firmware_update::UpdateFirmwareReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_UpdateFirmware<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UpdateFirmware : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateFirmware() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UpdateFirmware() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateFirmware(::grpc::ServerContext* /*context*/, const ::onvif_firmware_update::UpdateFirmwareRequest* /*request*/, ::onvif_firmware_update::UpdateFirmwareReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateFirmware : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateFirmware() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UpdateFirmware() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateFirmware(::grpc::ServerContext* /*context*/, const ::onvif_firmware_update::UpdateFirmwareRequest* /*request*/, ::onvif_firmware_update::UpdateFirmwareReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateFirmware(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateFirmware : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateFirmware() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateFirmware(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateFirmware() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateFirmware(::grpc::ServerContext* /*context*/, const ::onvif_firmware_update::UpdateFirmwareRequest* /*request*/, ::onvif_firmware_update::UpdateFirmwareReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateFirmware(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateFirmware : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateFirmware() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::onvif_firmware_update::UpdateFirmwareRequest, ::onvif_firmware_update::UpdateFirmwareReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::onvif_firmware_update::UpdateFirmwareRequest, ::onvif_firmware_update::UpdateFirmwareReply>* streamer) {
                       return this->StreamedUpdateFirmware(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateFirmware() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateFirmware(::grpc::ServerContext* /*context*/, const ::onvif_firmware_update::UpdateFirmwareRequest* /*request*/, ::onvif_firmware_update::UpdateFirmwareReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateFirmware(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::onvif_firmware_update::UpdateFirmwareRequest,::onvif_firmware_update::UpdateFirmwareReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UpdateFirmware<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_UpdateFirmware<Service > StreamedService;
};

}  // namespace onvif_firmware_update


#endif  // GRPC_onvif_5ffirmware_5fupdate_2eproto__INCLUDED
