// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: onvif_firmware_update.proto
#ifndef GRPC_onvif_5ffirmware_5fupdate_2eproto__INCLUDED
#define GRPC_onvif_5ffirmware_5fupdate_2eproto__INCLUDED

#include "onvif_firmware_update.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace onvif_firmware_update {

// The greeter service definition.
class FirmwareUpdate final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status UpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::onvif_firmware_update::UpdateFirmwareReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::onvif_firmware_update::UpdateFirmwareReply>> AsyncUpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::onvif_firmware_update::UpdateFirmwareReply>>(AsyncUpdateFirmwareRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::onvif_firmware_update::UpdateFirmwareReply>* AsyncUpdateFirmwareRaw(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status UpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::onvif_firmware_update::UpdateFirmwareReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::onvif_firmware_update::UpdateFirmwareReply>> AsyncUpdateFirmware(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::onvif_firmware_update::UpdateFirmwareReply>>(AsyncUpdateFirmwareRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::onvif_firmware_update::UpdateFirmwareReply>* AsyncUpdateFirmwareRaw(::grpc::ClientContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_UpdateFirmware_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status UpdateFirmware(::grpc::ServerContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest* request, ::onvif_firmware_update::UpdateFirmwareReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateFirmware : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_UpdateFirmware() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UpdateFirmware() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateFirmware(::grpc::ServerContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest* request, ::onvif_firmware_update::UpdateFirmwareReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateFirmware(::grpc::ServerContext* context, ::onvif_firmware_update::UpdateFirmwareRequest* request, ::grpc::ServerAsyncResponseWriter< ::onvif_firmware_update::UpdateFirmwareReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UpdateFirmware<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_UpdateFirmware : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_UpdateFirmware() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UpdateFirmware() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateFirmware(::grpc::ServerContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest* request, ::onvif_firmware_update::UpdateFirmwareReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateFirmware : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_UpdateFirmware() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::onvif_firmware_update::UpdateFirmwareRequest, ::onvif_firmware_update::UpdateFirmwareReply>(std::bind(&WithStreamedUnaryMethod_UpdateFirmware<BaseClass>::StreamedUpdateFirmware, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_UpdateFirmware() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateFirmware(::grpc::ServerContext* context, const ::onvif_firmware_update::UpdateFirmwareRequest* request, ::onvif_firmware_update::UpdateFirmwareReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateFirmware(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::onvif_firmware_update::UpdateFirmwareRequest,::onvif_firmware_update::UpdateFirmwareReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UpdateFirmware<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_UpdateFirmware<Service > StreamedService;
};

}  // namespace onvif_firmware_update


#endif  // GRPC_onvif_5ffirmware_5fupdate_2eproto__INCLUDED
